import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/app/(components)/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ticket App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div className="flex flex-col h-full">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-default-text p-0 m-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
